version: '3.8'

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/express-backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - PORT=8080
    restart: always

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/express-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always